# Generated by Django 3.0.3 on 2020-02-07 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Farmer')),
            ],
        ),
    ]
